Update 09-functions.yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,7 +1,7 @@
 name: 09 - Using Functions
 
 on:
-    pull_request:
+    #pull_request:
     workflow_dispatch:
 
 jobs:
@@ -17,13 +17,16 @@ jobs:
             cat << EOF
             ${{ toJSON(github.event.pull_request.labels)}}
             EOF
+        - name: Test
+          if: ${{ !cancelled()}}
+          run: echo "test"
         - name: Bug step
           if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix')}}
           run: echo "I am a bug fiz"
-        - name: Sleep for 20 seconds
-          run: sleep 20
-        - name: Failing Step
-          run: exit 1
+#        - name: Sleep for 20 seconds
+#          run: sleep 20
+#        - name: Failing Step
+#          run: exit 1
         - name: I will be skipped
           if: ${{ success() }}
           run: echo "I will print if previous steps succeed"
